### ISSUE TITLE
Feature request: Support `AWSS3.S3Paths`

### ISSUE THREAD

**Issue by ericphanson** [PhilipVinc/TensorBoardLogger.jl#102]
Since tensorboard supports logdirs being in s3 directly, it would be nice to be able to write to s3 directly too!

**Comment by PhilipVinc** [comment]
I don’t have time to work on this and soon will leave for holidays.
However if you open a PR I’ll gladly review it quickly.

this should be as easy as changing the type restriction on the path from a string to a more general path

**Comment by ericphanson** [comment]
One hurdle is that `open` on an `S3Path` returns an `FilePathsBase.FileBuffer <: IO` object but not an `IOStream`. So those types would need to be widened too. We could widen to `IO` if type stability is not a big problem here, or else add a depedency on FilePathsBase and type them as `Union{IOStream, FileBuffer}`. 

Also, there isn't really a common supertype of `String` and `S3Path`, but could do `Union{String, AbstractPath}` if we added a dep on FilePathsBase. Or just `Any` if type stability here isn't a bottleneck. I'm guessing often the 20 microseconds of dynamic dispatch is less than the cost of IO but I don't really know how TensorBoardLogger works.
