### ISSUE TITLE
Support `Base.close`?

### ISSUE THREAD

**Issue by darsnack** [PhilipVinc/TensorBoardLogger.jl#108]
I am using a machine with a network file system, and I am following a REPL-based dev flow. When I run the code to initialize the `TBLogger` (for a second time), I get a "resource busy" message from the OS.

It would be nice to support `Base.close(::TBLogger)` which performs the first part of `reset!(::TBLogger)` by releasing all the file handles.

**Comment by PhilipVinc** [comment]
PR welcome!
I don't have the bandwidth to do it myself.
I can promise a speedy review if you open it

**Comment by PhilipVinc** [comment]
can you add tests checking that close works / what happens if you close then it finalise?
