### ISSUE TITLE
Documentation URL on GitHub points to wrong location

### ISSUE THREAD

**Issue by JamieMair** [PhilipVinc/TensorBoardLogger.jl#111]
The Github Pages deployment points to https://philipvinc.github.io/TensorBoardLogger.jl, whereas the documentation (as far as I can tell) is hosted at https://julialogging.github.io/TensorBoardLogger.jl/dev/

Found the first link at https://github.com/JuliaLogging/TensorBoardLogger.jl/deployments/activity_log?environment=github-pages

**Comment by PhilipVinc** [comment]
I don't understand what is the problem exactly.
If you think it's an issue, can you open a PR fixing it?

**Comment by JamieMair** [comment]
I just submitted a PR - I think when this project was transferred to JuliaLogging, the source stayed pointed to the personal repo instead

**Comment by JamieMair** [comment]
Can confirm this works as expect, most recent deployment link at https://github.com/JuliaLogging/TensorBoardLogger.jl/deployments/activity_log?environment=github-pages points to the right URL
