### ISSUE TITLE
Add API for saving hyperparameters

### ISSUE THREAD

**Issue by JamieMair** [PhilipVinc/TensorBoardLogger.jl#112]
Tensorboard supports logging hyperparameters (see [here](https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams)). It would be good if there were an option when creating a logger to specify the hyperparameters of the run so they they can be view in the HParams section of tensorboard.

**Comment by JamieMair** [comment]
I should have checked the existing - this is already a request! - https://github.com/JuliaLogging/TensorBoardLogger.jl/issues/77

**Comment by PhilipVinc** [comment]
Yeah it would be nice.
The most up to date work on it is #99 , but some extra work is needed. 
If you wanted to do the work, it would be great, but I don't have the time to do this and probably never will have, though I can offer some guidance

**Comment by JamieMair** [comment]
@PhilipVinc I would be happy to try and work on this, let me know what needs doing.

**Comment by PhilipVinc** [comment]
Ok, let's move the discussion to #77 though
