### ISSUE TITLE
bump version for serialization bug fix 

### ISSUE THREAD

**Issue by nikopj** [PhilipVinc/TensorBoardLogger.jl#134]
the serialization bug fix #132 has yet to be released.

**Comment by CarloLucibello** [comment]
@nomadbl or anyone else, could you tag a release?

**Comment by nomadbl** [comment]
I actually don't know how to do that.
@oxinabox

**Comment by oxinabox** [comment]
You post a comment on the commit like so:
https://github.com/JuliaLogging/TensorBoardLogger.jl/commit/3d9c1a554a08179785459ad7b83bce0177b90275#commitcomment-125689946

Details:
https://github.com/JuliaRegistries/Registrator.jl#triggering-new-releases-from-the-main-branch-via-the-github-app
