### ISSUE TITLE
Register packge

### ISSUE THREAD

**Issue by oxinabox** [PhilipVinc/TensorBoardLogger.jl#14]
I think now is a good time to register the package,
as v0.1.0
so still Alpha by semver standards

**Comment by PhilipVinc** [comment]
It's high on my to-do list. 
I want to sketch out how to start implementing wrapper types, update the README and then I'll register.

**Comment by oxinabox** [comment]
I would register now, quietly. 0.1.0
and then do a more public 0.2.0 release once those things are done

**Comment by PhilipVinc** [comment]
Seems fine. Let's see if this works...

@JuliaRegistrator register()

**Comment by PhilipVinc** [comment]
@JuliaRegistrator register()

**Comment by PhilipVinc** [comment]
@JuliaRegistrator register()
