### ISSUE TITLE
Use Requires.jl to make LightGraphs a soft dependency?

### ISSUE THREAD

**Issue by oxinabox** [PhilipVinc/TensorBoardLogger.jl#39]
It would mean that logging graphs would only be enabled in you had LightGraphs loaded.

But then we can cut down our dependencies significantly.

**Comment by PhilipVinc** [comment]
I'm personally in favor of anything that cuts down on the dependencies of this package.
But, didn't you have reservations against using `Requires.jl` ? Or those issues have been fixed?

**Comment by oxinabox** [comment]
I do have reservations about `Requires.jl`,
it causes a big increase in load time when you load the package that is hidden behind it gets loaded.

but I think that is worth it to drop the dependency.

It also voids your ability to check versions of the Required package, but that is not so bad since we only use fairly basic functions that are unlikely to change
