### ISSUE TITLE
Unpacking/Preprocess-ing of Dictionaries

### ISSUE THREAD

**Issue by PhilipVinc** [PhilipVinc/TensorBoardLogger.jl#47]
Following #46 I realised that Optimums stores optimisation metadata in Dictionaries.

Right now, if a dictionary is logged to `TBLogger` (or if it's found while unpacking other structs) it is treated like any other struct, and it's internal fields are recursively logged:
```
Julia> using TensorBoardLogger
julia> data = TensorBoardLogger.preprocess("dict", Dict(:a=>1, :b=>2), [])
8-element Array{Any,1}:
    "dict/slots" => UInt8[0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
     "dict/keys" => Symbol[:a, :b, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef, #undef]
     "dict/vals" => [1, 2, 32, 1, 11, 2, 4628399872, 108, 24, 4628399872, 4628400112, 4628402464, 4628400112, 4628398656, 4628400112, 4426404768]
     "dict/ndel" => 0
    "dict/count" => 2
      "dict/age" => 0x0000000000000002
 "dict/idxfloor" => 1
 "dict/maxprobe" => 0
```

I think we should treat dictionaries with `String` and `Symbol` keys as we treat structures, and further preprocess key-value pairs.

Although, people often don't specialise the key type and use `Dict{Any,Any}` (Optim does that).
In this case, we could check if a string representation of every key exists, otherwise log them both as text?

**Comment by PhilipVinc** [comment]
We could add something like
```
## Default unpacking of key-value dictionaries
function preprocess(name, dict::Dict, data)
    i=1
    for k=keys(dict)
        if isa(k, String) || isa(k, Symbol) || isa(k, Real)
            preprocess(name*"/$k", dict[k], data)
        else
            tag = name*"/not_a_string_$i"
            preprocess(tag*"/key", k, data)
            preprocess(tag*"/val", dict[k], data)
            i += 1
        end
    end
    return data
end
```

which results in 
```
julia> data = TensorBoardLogger.preprocess("dict", Dict(:d=>1, 14=>2, 12+3im=>3, 123+7im=>"hey"), [])
8-element Array{Any,1}:
 "dict/not_a_string_1/key/re" => 123
 "dict/not_a_string_1/key/im" => 7
    "dict/not_a_string_1/val" => "hey"
                    "dict/14" => 2
                     "dict/d" => 1
 "dict/not_a_string_2/key/re" => 12
 "dict/not_a_string_2/key/im" => 3
    "dict/not_a_string_2/val" => 3```
```
It should allow us to cover the usual case of untyped Dicts with string keys, while also managing weird cases.
In any case I doubt that people will throw weird types in dicts they send to TBLogger.-

**Comment by tkf** [comment]
Hi, I just want to thank that this feature is implemented and released amazingly quickly!
