### ISSUE TITLE
Support StatsBase.Histogram

### ISSUE THREAD

**Issue by oschulz** [PhilipVinc/TensorBoardLogger.jl#62]
Since TBL already supports `(bins,weights)`, it would be cool it it could support `StatsBase.Histogram` directly as well.

**Comment by PhilipVinc** [comment]
1D histogram, that's easy. 
ND histograms. How and where?

**Comment by oschulz** [comment]
I just meant 1D histograms.

I guess 2D histograms could be supported via Plots, but I maybe the user should better do that explicitly.

**Comment by PhilipVinc** [comment]
Have a look at the #histogram-support branch and let me know

```Julia
] add TensorBoardLogger#histogram-support
```

**Comment by oschulz** [comment]
Just tried, seems to work fine, thanks!!

**Comment by PhilipVinc** [comment]
Closed by #63

**Comment by oschulz** [comment]
Thanks!!
