### ISSUE TITLE
set default step increment

### ISSUE THREAD

**Issue by CarloLucibello** [PhilipVinc/TensorBoardLogger.jl#65]
Hi, 
I am working on a Flux's model zoo example using TensorBoardLogger.jl
https://github.com/FluxML/model-zoo/pull/209
I don't use the automatic step increment, just manually set the step:
```julia
TensorBoardLogger.set_step!(tblogger, epoch)
with_logger(tblogger) do
    @info "train" loss=train.loss  acc=train.acc   log_step_increment=0
    @info "test"  loss=test.loss   acc=test.acc    log_step_increment=0
end
```
In this case, it would be nice to set once and for all the default step size, something like:
```julia
TensorBoardLogger.set_step_increment!(tblogger, 0)
```
Would you consider adding this feature?

**Comment by PhilipVinc** [comment]
Yes

The only thing that comes to my mind is whever  this should be module - level or per logger object.

But I’d go for object, as you proposed.

Maybe @oxinabox is opinionated on the subject.

Would you do a PR? You can just add a field to TBLogger and a kwarg to the constructor plus a method to modify it.
Il 5 mar 2020, 05:16 +0100, Carlo Lucibello <notifications@github.com>, ha scritto:

**Comment by oxinabox** [comment]
Per logger shounds right to me.
Though I don't particularly see the use myself.
