### ISSUE TITLE
Error after serializing and deserializing a TBLogger

### ISSUE THREAD

**Issue by DevJac** [PhilipVinc/TensorBoardLogger.jl#93]
I don't know if this is expected to work or not, but I serialized a TBLogger with the BSON package and then deserialized it in another Julia session and ended up getting errors because the file handles were bad. I created a work around, but is this something that TBLogger could handle internally? For example, it could check file handles are valid and re-open the files if needed.

**Comment by oxinabox** [comment]
In general julia has not made filehandles serializable. Presumably with good reason.
I assume because you can't be sure what is going on with that file outside of your enviroment.
It could have been deleted, it could have been replaced, etc.
Serializing the TBLogger in the first place doesn't seem useful.

**Comment by PhilipVinc** [comment]
Can I ask in what context this came up? In general TBLogger is already serialising data, so just can simply recreate it by recreating it with the right init policy (append, I guess)

**Comment by DevJac** [comment]
Sure. I'm doing some machine learning and have a struct filled with a variety of things which used to be globals. I put them in a struct for obvious reasons (I think). One of the global things that ended up in this struct is a very long lived TBLogger. I periodically serialize this struct to save the "global state" of my machine learning, so I can resume where I left off in case of a crash. And rather than access the TBLogger using scope, I pass around this struct, which contains a lot of configuration as well, as an explicit argument to many functions.

Again, a TBLogger is part of that struct, so it got serialized and then deserialized. Part of my confusion is log_histogram didn't fail, but a later log_value did, when flush was called. Once I realized the issue, that file handles cannot be serialized, the fix/workaround was easy.

And since you mentioned tb_append, this is how I create my TBLogger:
```
    tb_log = TBLogger("tb_logs/agent", tb_append)
    set_step!(tb_log, maximum(TensorBoardLogger.steps(tb_log)))
```
Just using `tb_append` by itself didn't behave as I expected, I thought it would resume logging from the previous global step.

I appreciate the clarification. I wouldn't expect file handles to be serializable. I can see a case for TBLogger automatically refreshing the file handles, and I can see a case for it not doing so. Although, since you point TBLogger to a directory and then let it create and modify files as needed, TBLogger could automatically "refresh" file handles, since it generally does whatever it wants in the directory anyway.
